name: Deploy Portfolio

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./ 
        env:
          GITHUB_TOKEN: ${{ secrets.LOCAL_MAC_TOKEN }}
